<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_wishlist-icon</name>
   <tag></tag>
   <elementGuidId>b6e37c19-a282-4907-9820-e6e23527049c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wishlist-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-section&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;container mt25 offset-0&quot;]/div[@class=&quot;col-md-12 offset-0&quot;]/div[@class=&quot;col-md-1 offset-0&quot;]/ul[@class=&quot;nav profile-tabs&quot;]/li[3]/a[1]/span[@class=&quot;wishlist-icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
